"""new-triboon

Revision ID: acd0aeaac9b0
Revises: 
Create Date: 2024-08-16 12:49:31.437034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd0aeaac9b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tell_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='teacher_pk'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_type_pk')
    )
    op.create_table('practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.Text(length=4096), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='practice_pk')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tell_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='user_pk'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('media_acsess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('TEXT', 'PHOTO', 'DOCUMENT', 'VIDEO', 'VOICE', 'AUDIO', 'VIDEO_NOTE', name='mediatype'), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Enum('USER', 'TEACHER', name='userlevel'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='media_acsess_pk')
    )
    op.create_table('user_practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('TEXT', 'PHOTO', 'DOCUMENT', 'VIDEO', 'VOICE', 'AUDIO', 'VIDEO_NOTE', name='mediatype'), nullable=True),
    sa.Column('caption', sa.Text(length=4096), nullable=True),
    sa.Column('file_link', sa.Text(length=100), nullable=True),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_practice_pk')
    )
    op.create_table('correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('user_practice_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('TEXT', 'PHOTO', 'DOCUMENT', 'VIDEO', 'VOICE', 'AUDIO', 'VIDEO_NOTE', name='mediatype'), nullable=True),
    sa.Column('caption', sa.Text(length=4096), nullable=True),
    sa.Column('file_link', sa.Text(length=100), nullable=True),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_practice_id'], ['user_practice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='correction_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correction')
    op.drop_table('user_practice')
    op.drop_table('media_acsess')
    op.drop_table('user')
    op.drop_table('practice')
    op.drop_table('user_type')
    op.drop_table('teacher')
    # ### end Alembic commands ###
